apiVersion: apps/v1
kind: Deployment
metadata:
  name: magoya
  namespace: magoya
  labels:
    app: magoya
spec:
  selector:
    matchLabels:
      app: magoya
  template:
    metadata:
      labels:
        app: magoya
    spec:
      containers:
      - name: magoya
        image: "nahuels/magoya-app:0.2.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits :
            memory : "1Gi"
          requests :
            memory : "250Mi"