name: Main Branch App Check
on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
    buildApp:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20.x'
          - name: Clean install and Build
            run: |
              npm ci
              npm run build --if-present
            working-directory: ./app/simple-homepage
    dockerizeApp:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/magoya-app:latest
            context: ./app/simple-homepage/.

    buildInfra:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.1.7"
            plan_only: true

        - name: Terraform Init
          id: init
          run: terraform init
          working-directory: ./app/simple-homepage

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color
          continue-on-error: true
          working-directory: ./app/simple-homepage
        deploy:
        name: Terraform Deploy
        needs: plan
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v3
          - name: Use Node.js 14.x
            uses: actions/setup-node@v1
            with:
              node-version: 14.x
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-west-1
          - name: Initialise project and deploy terraform
            run: |
              terraform apply --auto-approve=true